using System.Xml.Serialization;
using System;
using System.Globalization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace AnimeRecs.MalApi
{

    /// <summary>
    /// Not for use by outside assemblies.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    // Only public because the serializer insists on it
    public partial class myanimelist
    {
        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("anime", typeof(myanimelistAnime), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("myinfo", typeof(myanimelistMyinfo), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [XmlElement("error", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Error { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class myanimelistAnime
    {
        private string series_titleField;
        private string series_synonymsField;
        private string series_episodesField;
        private string series_statusField;
        private string series_imageField;
        private string my_idField;
        private string my_rewatchingField;
        private string my_rewatching_epField;
        private string my_last_updatedField;
        private string my_tagsField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int")]
        public int series_animedb_id
        {
            get
            {
                return SeriesAnimeDbId ?? 0;
            }
            set
            {
                SeriesAnimeDbId = value;
            }
        }
        [XmlIgnore]
        public int? SeriesAnimeDbId { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string series_title
        {
            get
            {
                return this.series_titleField;
            }
            set
            {
                this.series_titleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string series_synonyms
        {
            get
            {
                return this.series_synonymsField;
            }
            set
            {
                this.series_synonymsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int")]
        public int series_type
        {
            get { return SeriesType ?? 0; }
            set { SeriesType = value; }
        }
        [XmlIgnore]
        public int? SeriesType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string series_episodes
        {
            get
            {
                return this.series_episodesField;
            }
            set
            {
                this.series_episodesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string series_status
        {
            get
            {
                return this.series_statusField;
            }
            set
            {
                this.series_statusField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string series_start { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string series_end { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string series_image
        {
            get
            {
                return this.series_imageField;
            }
            set
            {
                this.series_imageField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string my_id
        {
            get
            {
                return this.my_idField;
            }
            set
            {
                this.my_idField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int")]
        public int my_watched_episodes
        {
            get { return NumEpisodesWatched ?? 0; }
            set { NumEpisodesWatched = value; }
        }
        [XmlIgnore]
        public int? NumEpisodesWatched { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string my_start_date { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string my_finish_date { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "decimal")]
        public decimal my_score
        {
            get
            {
                return MyScore ?? 0m;
            }
            set
            {
                MyScore = value;
            }
        }

        // Score of 0 in the xml means the user has not given a score.
        private decimal? m_score = null;
        [XmlIgnore]
        public decimal? MyScore { get { return m_score; } set { m_score = value == 0m ? null : value; } }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int")]
        public int my_status
        {
            get
            {
                return Status ?? 0;
            }
            set
            {
                Status = value;
            }
        }
        [XmlIgnore]
        public int? Status { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string my_rewatching
        {
            get
            {
                return this.my_rewatchingField;
            }
            set
            {
                this.my_rewatchingField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string my_rewatching_ep
        {
            get
            {
                return this.my_rewatching_epField;
            }
            set
            {
                this.my_rewatching_epField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string my_last_updated
        {
            get
            {
                return this.my_last_updatedField;
            }
            set
            {
                this.my_last_updatedField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string my_tags
        {
            get
            {
                return this.my_tagsField;
            }
            set
            {
                this.my_tagsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class myanimelistMyinfo
    {
        private string user_watchingField;

        private string user_completedField;

        private string user_onholdField;

        private string user_droppedField;

        private string user_plantowatchField;

        private string user_days_spent_watchingField;

        // For use by the deserializer, not by consuming code.
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "int")]
        public int user_id
        {
            get { return UserId ?? 0; }
            set { UserId = value; }
        }
        [XmlIgnore]
        public int? UserId { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_name
        {
            get { return Username; }
            set { Username = value; }
        }
        [XmlIgnore]
        public string Username { get; set; }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_watching
        {
            get
            {
                return this.user_watchingField;
            }
            set
            {
                this.user_watchingField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_completed
        {
            get
            {
                return this.user_completedField;
            }
            set
            {
                this.user_completedField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_onhold
        {
            get
            {
                return this.user_onholdField;
            }
            set
            {
                this.user_onholdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_dropped
        {
            get
            {
                return this.user_droppedField;
            }
            set
            {
                this.user_droppedField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_plantowatch
        {
            get
            {
                return this.user_plantowatchField;
            }
            set
            {
                this.user_plantowatchField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_days_spent_watching
        {
            get
            {
                return this.user_days_spent_watchingField;
            }
            set
            {
                this.user_days_spent_watchingField = value;
            }
        }
    }
}

/*
 Copyright 2011 Greg Najda

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/